name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment:
      name: Production
      url:  http://34.180.39.161/

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build & Push paylo-client
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/paylo-client/Dockerfile
          push: true
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          tags: geekyprogrammer07/paylo-client:latest
          cache-from: type=registry,ref=geekyprogrammer07/paylo-client:cache
          cache-to: type=registry,ref=geekyprogrammer07/paylo-client:cache,mode=max

      - name: Build & Push paylo-merchant
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/paylo-merchant/Dockerfile
          push: true
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          tags: geekyprogrammer07/paylo-merchant:latest
          cache-from: type=registry,ref=geekyprogrammer07/paylo-merchant:cache
          cache-to: type=registry,ref=geekyprogrammer07/paylo-merchant:cache,mode=max

      - name: Build & Push bank-webhook
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/bank-webhook/Dockerfile
          push: true
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          tags: geekyprogrammer07/paylo-bank:latest
          cache-from: type=registry,ref=geekyprogrammer07/paylo-bank:cache
          cache-to: type=registry,ref=geekyprogrammer07/paylo-bank:cache,mode=max

      - name: Verify Pushed Image
        run: docker pull geekyprogrammer07/paylo-client:latest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploying to Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: "suman"
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/paylo
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -af